### ISSUE TITLE
21w15a crash to desktop

### ISSUE THREAD

**Issue by GamingWithFusion** [MichaelHillcox/XRay-Fabric#11]
**Describe the bug**
Crashing when entering menu with "g", or even enabling the xray.

**To Reproduce**
1. Press g or backslash to enable x-ray
2. Instantly says "loading world..." and crashes.

**Expected behavior**
I expect the GUI to open so I can configure settings, or be able to use the x-ray.

**Minecraft Environment**
 - Minecraft Version: [21w15a]
 - XRay Mod Version: [0.5.0s]
 - Using latest Fabric for 21w15a

**Additional context**
I'd definitely like to see an update to the fabric addition for the latest snapshot since the last released version was for 21w06a. The crash could possibly because of the Caves&CliffsPreview data pack, but I am entirely unsure and I will be awaiting for a reply.

**Crash Report**
- 
java.lang.NoSuchMethodError: com.mojang.blaze3d.systems.RenderSystem.pushMatrix()V
	at pro.mikey.fabric.xray.screens.forge.GuiBase.method_25394(GuiBase.java:54)
	at net.minecraft.class_757.method_3192(class_757.java:840)
	at net.minecraft.class_310.method_1523(class_310.java:1073)
	at net.minecraft.class_310.method_1514(class_310.java:700)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

**Comment by MichaelHillcox** [comment]
It's not built for that snapshot yet, and likely won't be for a while as the render engine has changed a lot

**Comment by GamingWithFusion** [comment]
Yeah, I do know it's only for 21w06a. Thanks for the response, I'll definitely not take it too seriously. Definitely hard to make a mod for snapshots that always changes. Does prepare for the final release though. I am excited about 1.17's release so we can get the Forge version going, and I'd imagine that's much more stable. Thanks for your time, you definitely have a life to live before worrying about this. Thanks again, hope you have a good day.

> I'll leave this comment open so you can use it for future reference to update, but feel free to close it if you don't need it.
