### ISSUE TITLE
Game crash when open the config UI

### ISSUE THREAD

**Issue by ALiangLiang** [MichaelHillcox/XRay-Fabric#14]
**Describe the bug**
Press G to open config UI and crash

**To Reproduce**
1. open the game and enter server

**Expected behavior**
It should open UI

**Screenshots**
If applicable (delete if not), add screenshots to help explain your problem.

**Minecraft Enviorment**
 - Minecraft Version: 1.17
 - XRay Mod Version: advanced-xray-fabric-21w06a-0.5.0s.jar
 - Mod Pack & Version if applicable
 ```
		advanced-xray-fabric: Advanced XRay (Fabric) 0.5.0s
		architectury: Architectury 2.0.7
		autoreconnect: AutoReconnect 1.1.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		crowdin-translate: CrowdinTranslate 1.3+1.17
		durabilityviewer: Giselbaers Durability Viewer 1.17-fabric0.34.9-1.10
		easiervillagertrading: EasierVillagerTrading 1.17-fabric0.34.9-1.5.3
		fabric: Fabric API 0.34.9+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b4463d5
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.2+a02b4463d5
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+9e521e13d5
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b4463d5
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b4463d5
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afad5
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b4463d5
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b4463d5
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da310d5
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b4463d5
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b4463d5
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.8+a02b4463d5
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afad5
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b4463d5
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b4463d5
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab6121d5
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b4463d5
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3ed5
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b4463d5
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b4463d5
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afad5
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b4463d5
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab6121d5
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b4463d5
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afad5
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab6121d5
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b4463d5
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b4463d5
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.9+a02b4463d5
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+a02b4463d5
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b4463d5
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b4463d5
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b4463d5
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b4463d5
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afad5
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b4463d5
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab6121a0
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.3+b7ab6121d5
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b4463d5
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.10+be9da310d5
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b4463d5
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b4463d5
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab6121d5
		fabricloader: Fabric Loader 0.11.3
		gbfabrictools: GBfabrictools 1.3.4+1.17
		itemscroller: Item Scroller 0.15.0-dev.20210608.211652
		java: OpenJDK 64-Bit Server VM 16
		litematica: Litematica 0.0.0-dev.20210608.211719
		malilib: MaLiLib 0.10.0+dev.22
		minecraft: Minecraft 1.17
		minihud: MiniHUD 0.19.0-dev.20210608.211830
		mm: Manningham Mills 2.2
		modmenu: Mod Menu 2.0.0-beta.7
		shulkerboxtooltip: Shulker Box Tooltip 3.0.0-alpha.3+1.17
		tweakeroo: Tweakeroo 0.10.0-dev.20210608.211857
```
 - Forge Version if applicable: fabric 0.7.3

**Additional context**
```
Description: Unexpected error

java.lang.NoSuchFieldError: field_22791
	at pro.mikey.fabric.xray.screens.forge.GuiSelectionScreen.method_25426(GuiSelectionScreen.java:65)
	at net.minecraft.class_437.method_25423(class_437.java:387)
	at net.minecraft.class_310.method_1507(class_310.java:986)
	at pro.mikey.fabric.xray.XRay.clientTickEvent(XRay.java:63)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$zhk000$onEndTick(class_310.java:5573)
	at net.minecraft.class_310.method_1574(class_310.java:1808)
	at net.minecraft.class_310.method_1523(class_310.java:1083)
	at net.minecraft.class_310.method_1514(class_310.java:730)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
```

**Comment by PixelTomato** [comment]
The latest version of this mod on CurseForge [https://www.curseforge.com/minecraft/mc-mods/advanced-xray-fabric-edition/files](https://www.curseforge.com/minecraft/mc-mods/advanced-xray-fabric-edition/files) does not crash when the GUI is opened.

**Comment by ALiangLiang** [comment]
@PixelTomato Thx a lot. I got the latest version, but i forgot to close the issue.
